/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include <ifxCpu_Irq.h>
#include "IfxScuWdt.h"
#include "SmartCar_Uart.h"
#include "SmartCar_Upload.h"
#include "SmartCar_Oled.h"
#include "SmartCar_Pwm.h"
#include "SmartCar_MPU.h"
#include "SmartCar_MT9V034.h"
#include "SmartCar_Systick.h"
#include "SmartCar_GPIO.h"
#include "SmartCar_PIT.h"
#include "SmartCar_Encoder.h"
#include "common.h"
#include "image.h"
#include "menu.h"
#include "beacon_control.h"


#pragma section all "cpu0_dsram"
//IfxCpu_syncEvent g_cpuSyncEvent;
mpu_t* this_mpu;

int core0_main(void)
{
    IfxCpu_disableInterrupts();
    
    get_clk();
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /****初始化外设****/
    /*OLED初始化*/
    SmartCar_Oled_Init();
    /**/

    /*总钻风初始化*/
    SmartCar_MT9V034_Init();
    /**/

    /*外部中断初始化*/
//    Eru_Init();
    /**/

    /*PWM初始化*/
    Servo_motorinit();
    /**/

    /*编码器初始化*/
    Encoder_init();

    /*串口初始化*/
    SmartCar_Uart_Init(IfxAsclin0_TX_P14_0_OUT,IfxAsclin0_RXA_P14_1_IN,1152000,0);
    /**/

    /*GPIO初始化*/
    /*菜单用GPIO初始化*/
    Menu_gpioinit();
    /**/

    /*定时中断初始化*/
//    Pit_Init_ms(CCU6_0,PIT_CH0,500);
//    Pit_Enable_Interrupt(CCU6_0,PIT_CH0);
//    Pit_Start(CCU6_0,PIT_CH0);
    /**/

    /*ADC初始化*/
//  ADC_Init();
    /**/

    IfxCpu_enableInterrupts();


    /*初始化菜单*/
//    SmartCar_OLED_Fill(0);
//    MENU_Tree();
    /*显示首页面*/
//    MENU_Start();
//    MENU_Read();
    /**/

    /*初始化mpu*/
    SmartCar_MPU_Set_DefaultConfig(this_mpu);
    SmartCar_MPU_Init2(this_mpu);
    SmartCar_GyroOffset(this_mpu);
    /**/

    while(TRUE)
    {
        while(!mt9v034_finish_flag){}
        mt9v034_finish_flag = 0;
        //SmartCar_Show_IMG(&mt9v034_image[0][0],120,188);
        /*按键操作*/
        //MENU_Make();
        //采图
        //SmartCar_ImgUpload((uint8*)mt9v034_image,120,188);  //采图用函数
    }
}


IFX_INTERRUPT(cc60_pit_ch0_isr, 0, CCU6_0_CH0_ISR_PRIORITY)
{
    enableInterrupts();//开启中断嵌套
    PIT_CLEAR_FLAG(CCU6_0, PIT_CH0);
}

#pragma section all restore
