/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include <ifxCpu_Irq.h>
#include "IfxScuWdt.h"
#include "SmartCar_Uart.h"
#include "SmartCar_Upload.h"
#include "SmartCar_Oled.h"
#include "SmartCar_Pwm.h"
#include "SmartCar_MPU.h"
#include "SmartCar_MT9V034.h"
#include "SmartCar_Systick.h"
#include "SmartCar_GPIO.h"
#include "SmartCar_PIT.h"
#include "SmartCar_Encoder.h"
#include "SmartCar_ADC.h"
#include "common.h"
#include "image.h"
#include "menu.h"
#include "beacon_control.h"
#include "testsome.h"
#include "lib_pidctrl.h"
#include "VA_get.h"



#pragma section all "cpu0_dsram"
//IfxCpu_syncEvent g_cpuSyncEvent;
mpu_t* this_mpu;
float time;
float myvar[8] = {0};
extern int16 leftFTM;
extern int16 rightFTM;
/*电压电流采集值*/
extern float battery;
extern float Icharge;
/**/


/*extern专区*/
extern int lightsensor[4];
extern int mode_flag;
extern int error_simu;
extern float servo_pulse;
extern int light_flag;
extern int aver_x;
extern int simu_y;
extern int motordutyset;
extern float motor_rigdevn;
extern float motor_lefdevn;

/**/


extern uint32_t motor_lefdevnU;
extern uint32_t motor_rigdevnU;
extern uint32_t N_motor_lefdevnU,N_motor_rigdevnU;
extern uint8 connectnum;
extern int areaA_time;
extern uint32_t servofinal;
extern int servodirection;
extern float lighty;
extern int aver_y;
extern float lightx,lights,lightc;
extern int servoduty;

/*oled灯和图像的切换*/
int mode = 0;


int core0_main(void)
{
    IfxCpu_disableInterrupts();

    get_clk();
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /****初始化外设****/
    /**/

    /*总钻风初始化*/
    SmartCar_MT9V034_Init();
    /**/
    /*定时中断初始化*/
    /*电机*/
    Pit_Init(CCU6_0,PIT_CH0,5*1000);
//    Pit_Enable_Interrupt(CCU6_0,PIT_CH0);
//    Pit_Start(CCU6_0,PIT_CH0);
    //充电
    Pit_Init(CCU6_1,PIT_CH0,9*1000);
//    /*舵机*/
    Pit_Init(CCU6_1,PIT_CH1,20*1000);

    /*PWM初始化*/
    Servo_motorinit();
    /**/

    /*编码器初始化*/
    Encoder_init();

    /*串口初始化*/
    SmartCar_Uart_Init(IfxAsclin0_TX_P14_0_OUT,IfxAsclin0_RXA_P14_1_IN,1152000,0);
    SmartCar_Uart_Init(IfxAsclin2_TX_P10_5_OUT,IfxAsclin2_RXD_P10_6_IN,921600,2);
    /**/

    /*GPIO初始化*/
    /*菜单用GPIO初始化*/
    Menu_gpioinit();

    /*光电管*/
    GuangDian_Init();
//
//    /*ADC初始化*/
    ADC_Init(ADC_0,ADC0_CH8_A8);
    ADC_Init(ADC_0,ADC0_CH11_A11);
    /**/

////    /*电机舵机测试*/
//    SmartCar_Gtm_Pwm_Setduty(&IfxGtm_ATOM1_1_TOUT31_P33_9_OUT,860);
////    /**/
//
    /*外部中断初始化*/
    Eru_Init(CH5_P15_8,FALLING);


    /**/
    /*OLED初始化*/
    SmartCar_Oled_Init();
    /*初始化菜单*/
    SmartCar_OLED_Fill(0);
    MENU_Tree();
    /*显示首页面*/
    MENU_Start();
    MENU_Read();

    IfxCpu_enableInterrupts();

    /*初始化mpu*/
//    SmartCar_MPU_Set_DefaultConfig(this_mpu);
//    SmartCar_MPU_Init2(this_mpu);
//    SmartCar_GyroOffset(this_mpu);
    /**/
//
    while(TRUE)
    {
//        while(!mt9v034_finish_flag){}
//            mt9v034_finish_flag = 0;
//        Systick_Start(STM0);
//        THRE();
//        image_main();
//        time = GetTime_ms(STM0);
//        myvar[0] = time;
//        /*测输入电压电流*/
//        GetVA();
//        myvar[1] = CV_IN;
//        myvar[2] = CA_IN; //电流
//        lightsensor[0] = GPIO_Read(P15,4);
//        lightsensor[1] = GPIO_Read(P11,10);
//        lightsensor[2] = GPIO_Read(P33,7);
//        lightsensor[3] = GPIO_Read(P20,9);
//        myvar[0] = lightsensor[0];
//        myvar[1] = lightsensor[1];
//        myvar[2] = lightsensor[2];
//        myvar[3] = lightsensor[3];

        myvar[4] = servofinal;
        myvar[5] = servodirection;
        myvar[6] = servo_pulse;
//        myvar[7] = ;

        myvar[8] = Icharge;
        /*显示图像*/
        if(mode == 0){
            MENU_Make();
        }
        /**/
        /*按键操作*/
        else if(mode == 1){
            SmartCar_Show_IMG(&IMG[0][0],120,188);
        }
        else if(mode == 2)
        {
            SmartCar_VarUpload(myvar,9);
        }
        else if(mode == 3){}

        /*采图*/
//      SmartCar_ImgUpload((uint8*)IMG,120,188);  //采图用函数
 //      SmartCar_ImgUpload((uint8*)mt9v034_image,120,188);  //采图用函数
       /**/
    }
}

/*定时器中断*/
/*20ms*/
IFX_INTERRUPT(cc60_pit_ch0_isr, 0, CCU6_0_CH0_ISR_PRIORITY)
{
    enableInterrupts();//开启中断嵌套
        leftFTM = -SmartCar_Encoder_Get(GPT12_T4);
        rightFTM = SmartCar_Encoder_Get(GPT12_T6);
        SmartCar_Encoder_Clear(GPT12_T4);
        SmartCar_Encoder_Clear(GPT12_T6);
    Motor_control();
    PIT_CLEAR_FLAG(CCU6_0, PIT_CH0);

}
/*5ms*/
IFX_INTERRUPT(cc61_pit_ch1_isr, 0, CCU6_1_CH1_ISR_PRIORITY)
{
    enableInterrupts();//开启中断嵌套
    Servo_control();
//    SmartCar_Gtm_Pwm_Setduty(&IfxGtm_ATOM1_1_TOUT31_P33_9_OUT,servoduty);
    PIT_CLEAR_FLAG(CCU6_1, PIT_CH1);
}
/*5ms*/
IFX_INTERRUPT(cc61_pit_ch0_isr, 0, CCU6_1_CH0_ISR_PRIORITY)
{
    enableInterrupts();//开启中断嵌套
//    Battery_Get();
    Icharge_Get();
    PIT_CLEAR_FLAG(CCU6_1, PIT_CH0);

}
/**/

/*外部中断*/
IFX_INTERRUPT(eru_ch1_ch5_isr, 0, ERU_CH1_CH5_INT_PRIO)
{
    enableInterrupts();//开启中断嵌套
    if(GET_GPIO_FLAG(CH1_P10_8))//通道1中断
    {
        CLEAR_GPIO_FLAG(CH1_P10_8);
    }
    if(GET_GPIO_FLAG(CH5_P15_8))//通道5中断
    {
        CLEAR_GPIO_FLAG(CH5_P15_8);
        mode++;
        if(mode == 4)
        {
            mode = 0;
        }
    }
}
/**/


#pragma section all restore
